name: preset
description: Advanced theme management system with string codec.
version: 0.0.1
homepage: https://github.com/rey-xi/preset/tree/master
repository: https://github.com/rey-xi/preset


environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
